<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Course extends Model
{
    use HasFactory , SoftDeletes;

    protected $fillable = [
        'id','teacher_id','description','title','created_at','updated_at','type'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($course) {
            foreach ($course->documents as $document) {
                $document->delete();
            }
        });
    }

    public function teacher(){
        return $this->belongsTo(Teacher::class);
    }

    public function students(){
        return $this->belongsToMany(Student::class);
    }

    public function lectures(){
        return $this->hasMany(Lecture::class);
    }

    public function assignments(){
        return $this->morphMany(Assignment::class,'assignmentable');
    }

    public function quizzes(){
        return $this->hasMany(Quiz::class);
    }

    public function advertisements(){
        return $this->hasMany(Advertisement::class);
    }

    public function documents()
    {
        return $this->morphMany(Document::class, 'documentable');
    }
}
